(()=>{'use strict';const $=id=>document.getElementById(id),all=window.OZ_MEDICINES||[],key='oznursehub-learning-v1';let persistent=true,state={saved:[],reviewed:[],attempts:0,correct:0};
try{const raw=JSON.parse(localStorage.getItem(key)||'null');if(raw&&typeof raw==='object'){const ids=new Set(all.map(r=>r.id));state.saved=[...new Set((Array.isArray(raw.saved)?raw.saved:[]).filter(id=>ids.has(id)))];state.reviewed=[...new Set((Array.isArray(raw.reviewed)?raw.reviewed:[]).filter(id=>ids.has(id)))];state.attempts=Number.isSafeInteger(raw.attempts)&&raw.attempts>=0?raw.attempts:0;state.correct=Number.isSafeInteger(raw.correct)&&raw.correct>=0&&raw.correct<=state.attempts?raw.correct:0;}localStorage.setItem(key,JSON.stringify(state));}catch{persistent=false;$('storage-warning').hidden=false;}
let deck=[],index=0,answered=false;
function persist(){if(persistent)try{localStorage.setItem(key,JSON.stringify(state));}catch{persistent=false;$('storage-warning').hidden=false;}stats();}
function stats(){$('reviewed').textContent=state.reviewed.length;$('saved-count').textContent=state.saved.length;$('attempted').textContent=state.attempts;$('accuracy').textContent=state.attempts?Math.round(100*state.correct/state.attempts)+'%':'—';}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function build(){deck=all.filter(r=>($('topic').value==='all'||r.group===$('topic').value)&&(!$('saved-only').checked||state.saved.includes(r.id)));index=0;render();}
function render(){const r=deck[index],empty=!r;$('practice-card').hidden=empty;$('empty-deck').hidden=!empty;$('save').disabled=empty;$('next').disabled=deck.length<2;$('previous').disabled=deck.length<2;$('shuffle').disabled=deck.length<2;$('position').textContent=empty?'No medicines in this deck':`${index+1} of ${deck.length} medicines`;if(empty)return;answered=false;const saved=state.saved.includes(r.id);$('save').setAttribute('aria-pressed',String(saved));$('save').textContent=saved?'★ Saved for revision':'☆ Save for revision';$('medicine-name').textContent=r.name.replace(/\*$/,'');$('drug-class').textContent=r.category;$('drug-uses').textContent=r.uses;$('drug-risks').textContent=r.risks;$('flash-answer').hidden=true;$('reveal').textContent='Reveal the card';$('reveal').setAttribute('aria-expanded','false');$('reference-link').href='medications.html#medicine-'+r.id;$('special-note').hidden=!r.note;$('special-note').textContent=r.note||'';const quiz=$('mode').value==='quiz';$('flash-mode').hidden=quiz;$('quiz-mode').hidden=!quiz;if(quiz)question(r);}
function question(r){$('quiz-question').textContent=`Which class is listed on the reference card for ${r.name.replace(/\*$/,'')}?`;$('quiz-feedback').hidden=true;$('quiz-feedback').replaceChildren();const alternatives=shuffle([...new Set(all.filter(other=>other.group!==r.group&&other.category!==r.category).map(other=>other.category))]).slice(0,3);const options=shuffle([r.category,...alternatives]);$('choices').replaceChildren();options.forEach(label=>{const button=document.createElement('button');button.type='button';button.className='choice';button.textContent=label;button.addEventListener('click',()=>answer(r,label,button));$('choices').append(button);});}
function answer(r,label,button){if(answered)return;answered=true;const correct=label===r.category;state.attempts++;if(correct)state.correct++;for(const choice of $('choices').children){choice.disabled=true;if(choice.textContent===r.category){choice.classList.add('correct');choice.textContent+=' — Correct answer';}}if(!correct){button.classList.add('incorrect');button.textContent+=' — Your answer';}const lead=document.createElement('strong');lead.textContent=correct?'Correct.':'Not quite — a useful one to revisit.';const explanation=document.createElement('p');explanation.textContent=`${r.name.replace(/\*$/,'')} is classified as ${r.category}. Selected uses: ${r.uses}. Key risks: ${r.risks}.`;$('quiz-feedback').append(lead,explanation);$('quiz-feedback').hidden=false;persist();}
$('reveal').addEventListener('click',()=>{const r=deck[index];if(!r)return;const open=$('flash-answer').hidden;$('flash-answer').hidden=!open;$('reveal').setAttribute('aria-expanded',String(open));$('reveal').textContent=open?'Hide the answer':'Reveal the card';if(open&&!state.reviewed.includes(r.id)){state.reviewed.push(r.id);persist();}});
$('save').addEventListener('click',()=>{const r=deck[index];if(!r)return;const saved=state.saved.includes(r.id);state.saved=saved?state.saved.filter(id=>id!==r.id):[...state.saved,r.id];persist();if($('saved-only').checked){deck=deck.filter(x=>state.saved.includes(x.id));index=Math.min(index,Math.max(0,deck.length-1));render();}else{$('save').setAttribute('aria-pressed',String(!saved));$('save').textContent=!saved?'★ Saved for revision':'☆ Save for revision';}});
$('next').addEventListener('click',()=>{if(deck.length){index=(index+1)%deck.length;render();}});$('previous').addEventListener('click',()=>{if(deck.length){index=(index+deck.length-1)%deck.length;render();}});$('shuffle').addEventListener('click',()=>{shuffle(deck);index=0;render();});$('topic').addEventListener('change',build);$('saved-only').addEventListener('change',build);$('mode').addEventListener('change',render);$('reset').addEventListener('click',()=>{$('reset-panel').hidden=false;$('confirm-reset').focus();});$('cancel-reset').addEventListener('click',()=>{$('reset-panel').hidden=true;$('reset').focus();});$('confirm-reset').addEventListener('click',()=>{state={saved:[],reviewed:[],attempts:0,correct:0};persist();$('reset-panel').hidden=true;build();$('reset').focus();});stats();build();
})();
